[2023-11-26T07:41:46.668+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetch_clean_elastic.post_to_elasticsearch manual__2023-11-26T07:38:37.714775+00:00 [queued]>
[2023-11-26T07:41:46.672+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetch_clean_elastic.post_to_elasticsearch manual__2023-11-26T07:38:37.714775+00:00 [queued]>
[2023-11-26T07:41:46.672+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-11-26T07:41:46.672+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2023-11-26T07:41:46.672+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-11-26T07:41:46.677+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): post_to_elasticsearch> on 2023-11-26 07:38:37.714775+00:00
[2023-11-26T07:41:46.681+0000] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2023-11-26T07:41:46.682+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_clean_elastic', 'post_to_elasticsearch', 'manual__2023-11-26T07:38:37.714775+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_Sifra_Siregar_DAG.py', '--cfg-path', '/tmp/tmp842bvt3m', '--error-file', '/tmp/tmpn_uuz_op']
[2023-11-26T07:41:46.683+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask post_to_elasticsearch
[2023-11-26T07:41:46.710+0000] {task_command.py:371} INFO - Running <TaskInstance: fetch_clean_elastic.post_to_elasticsearch manual__2023-11-26T07:38:37.714775+00:00 [running]> on host 159ad28653d9
[2023-11-26T07:41:46.739+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=sifra
AIRFLOW_CTX_DAG_ID=fetch_clean_elastic
AIRFLOW_CTX_TASK_ID=post_to_elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2023-11-26T07:38:37.714775+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-26T07:38:37.714775+00:00
[2023-11-26T07:41:46.761+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_Sifra_Siregar_DAG.py", line 136, in index_to_elasticsearch
    es.index(index=index_name, id=i, document=doc)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: index() got an unexpected keyword argument 'document'
[2023-11-26T07:41:46.766+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_clean_elastic, task_id=post_to_elasticsearch, execution_date=20231126T073837, start_date=20231126T074146, end_date=20231126T074146
[2023-11-26T07:41:46.770+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task post_to_elasticsearch (index() got an unexpected keyword argument 'document'; 293)
[2023-11-26T07:41:46.818+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-11-26T07:41:46.837+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
